Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using MovieProDemo.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using MovieProDemo.Services.Interfaces;

namespace MovieProDemo.Controllers
{
    public class ActorController : Controller
    {
        private readonly IDataMappingService _tmdbMappingService;
        private readonly IRemoteMovieService _tmdbMovieService;
        public ActorController(IRemoteMovieService tmdbMovieService, IDataMappingService tmdbMappingService)
        {
            _tmdbMappingService = tmdbMappingService;
            _tmdbMovieService = tmdbMovieService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var actor = await _tmdbMovieService.ActorDetailAsync(id);
            actor = _tmdbMappingService.MapActorDetail(actor);
            return View(actor);
        }
    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using MovieProDemo.Data;
using MovieProDemo.Models.Database;
using MovieProDemo.Models.Settings;
using MovieProDemo.Models.TMDB;
using MovieProDemo.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieProDemo.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly ApplicationDbContext _db;
        private readonly IImageService _imageService;
        private readonly IRemoteMovieService _tmdbMovieService;
        private readonly IDataMappingService _tmdbMappingService;
        public MoviesController(IOptions<AppSettings> appSettings,ApplicationDbContext db,IImageService imgService,IRemoteMovieService tmdbMovieService,IDataMappingService tmdbMappingService)
        {
            _appSettings = appSettings.Value;
            _db = db;
            _imageService = imgService;
            _tmdbMovieService = tmdbMovieService;
            _tmdbMappingService = tmdbMappingService;
        }
        public async Task<IActionResult> Import()
        {
            var movies = await _db.Movie.ToListAsync();

            return View(movies);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(int id)
        {
            //If we already have this movie we can just warn the user instead of importing it again
            if (_db.Movie.Any(m => m.Id == id))
            {
                var localMovie = await _db.Movie.FirstOrDefaultAsync(m => m.MovieId == id);
                return RedirectToAction("Details","Movies",new { id = localMovie.Id,local = true});
            }

            //Step 1: Get the raw data from the API
            var movieDetail = await _tmdbMovieService.MovieDetailAsync(id);

            //Step 2: Run the data through a mapping procedure
            var movie = await _tmdbMappingService.MapMovieDetailAsync(movieDetail);

            //Step 3: Add the new movie
            _db.Add(movie);
            await _db.SaveChangesAsync();

            //Step 4: Assign it to the default all collection
            await AddToMovieCollection(movie.Id,_appSettings.MovieProSettings.DefaultCollection.Name);

            return RedirectToAction("Import");
        }
        public async Task<IActionResult> Library()
        {
            var movies = await _db.Movie.ToListAsync();

            return View(movies);
        }
        // GET: Movie/Create
        public IActionResult Create()
        {
            ViewData["CollectionId"] = new SelectList(_db.Collection,"Id","Name");
            return View();
        }

        // POST: Movie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MovieId,Title,TagLine,Overview,RunTime,ReleaseDate,Rating,VoteAverage,Poster,PosterType,Backdrop,BackdropType,TrailerUrl")] Movie movie, int collectionId)
        {
            if (ModelState.IsValid)
            {
                movie.PosterType = movie.PosterFile?.ContentType;
                movie.Poster = await _imageService.EncodeImageAsync(movie.PosterFile);

                movie.BackdropType = movie.BackdropFile?.ContentType;
                movie.Backdrop = await _imageService.EncodeImageAsync(movie.BackdropFile);

                _db.Add(movie);
                await _db.SaveChangesAsync();

                await AddToMovieCollection(movie.Id,collectionId);

                return RedirectToAction("Index","MovieCollections");
            }
            return View(movie);
        }

        // GET: Movie/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _db.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieId,Title,TagLine,Overview,RunTime,ReleaseDate,Rating,VoteAverage,Poster,PosterType,Backdrop,BackdropType,TrailerUrl")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (movie.PosterFile is not null)
                    {
                        movie.PosterType = movie.PosterFile?.ContentType;
                        movie.Poster = await _imageService.EncodeImageAsync(movie.PosterFile);
                    }

                    if (movie.BackdropFile is not null)
                    {
                        movie.BackdropType = movie.BackdropFile?.ContentType;
                        movie.Backdrop = await _imageService.EncodeImageAsync(movie.BackdropFile);
                    }
                    //Add the movie to the db<set>
                    _db.Update(movie);

                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details","Movies", new { id = movie.Id, local = true});
            }
            return View(movie);
        }

        // GET: Movie/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _db.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _db.Movie.FindAsync(id);
            _db.Movie.Remove(movie);
            await _db.SaveChangesAsync();
            return RedirectToAction("Library","Movies");
        }
        public async Task<IActionResult> Details(int? id, bool isLocal = false)
        {
     
            if (id == null)
            {
                return NotFound();
            }

            Movie movie = new();

            if (isLocal == true)
            {
                //Get the data from the database
                movie = await _db.Movie.Include(m => m.Cast).Include(m => m.Crew).FirstOrDefaultAsync(m => m.Id == id);
            }
            else
            {
                //Get the data from the TMDB API
                MovieDetail movieDetail = await _tmdbMovieService.MovieDetailAsync((int)id);
                movie = await _tmdbMappingService.MapMovieDetailAsync(movieDetail);
            }

            if (movie == null)
            {
                return NotFound();
            }
            ViewData["Local"] = isLocal;
            return View(movie);
        }
        private bool MovieExists(int id)
        {
            return _db.Movie.Any(e => e.Id == id);
        }

        private async Task AddToMovieCollection(int movieId, string collectionName)
        {
            var collection = await _db.Collection.FirstOrDefaultAsync(c => c.Name == collectionName);
            _db.Add(
                new MovieCollection()
                {
                    CollectionId = collection.Id,
                    MovieId = movieId
                }
             );
            await _db.SaveChangesAsync();
        }
        private async Task AddToMovieCollection(int movieId,int collectionId)
        {
            _db.Add(
                new MovieCollection()
                {
                    CollectionId = collectionId,
                    MovieId = movieId
                }
            );

            await _db.SaveChangesAsync();
        }


    }
}

Views/Movies/Details.cshtml
@using MovieProDemo.Models.Database
@using MovieProDemo.Services.Interfaces
@model Movie
@inject IImageService _imageService

<div class="row">
    <div class="col-sm-12 col-md-6">
        <div class="row">
            <img src="@_imageService.DecodeImage(Model.Poster,Model.PosterType)" alt="Poster image" class="w-100"/>
        </div>
        <div class="row">
            <button class="btn btn-lg btn-danger w-100 font-weight-bold" data-toggle="modal" data-target="#trailer">
                WATCH TRAILER
            </button>
        </div>
    </div>
    <div class="col-sm-12 col-md-6">
        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">TITLE:</span> @Model.Title
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">RELEASED:</span> @Model.ReleaseDate.ToString("MMM dd, yyyy");
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">RATING:</span> @Model.Rating
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col h5">
                <span class="font-weight-bolder mr-2">REVIEWS:</span> @Model.VoteAverage / 10
            </div>
        </div>
        <hr />
        <div class="row mt-3 mb-2">
            <div class="col">
                <span class="h5 font-weight-bolder"> OVERVIEW:</span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <span class="h5 ml-4">@Model.Overview</span>
            </div>
        </div>
    </div>
  
</div>
<div class="row">
    <div class="col">
        <span class="h5 font-weight-bolder">STARRING:</span>
    </div>
</div>
@foreach(var actor in Model.Cast.Take(5)){
    <div class="row">
        <div class="col">
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-2">
                        <img src="@actor.ImageUrl" class="img-fluid" style="width: 10rem" alt="..."/>
                    </div>
                    <div class="col-md-10">
                        <div class="card-body">
                            <h5 class="card-title"><a asp-action="Details" asp-controller="Actor" asp-route-id="@actor.CastId">Name: @actor.Name</a></h5>
                            <p class="card-text">Character: @actor.Character</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<!--Modal-->
<div class="modal fade" id="trailer" tabindex="-1" role="dialog" aria-labelledby="trailerLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@Model.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="embed-responsive embed-responsive-16by9">
                    @{ 
                        //I am isolating a piece of data in order to use it as my embed source
                        var key = Model.TrailerUrl.Split("=").Last();
                        var source = $"https://www.youtube.com/embed/{key}";
                    }
                    <iframe width="560" height="315" src="@source"
                            title="YouTube video player" frameborder="0"
                            allow="accelormeter; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen>

                    </iframe>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>